defaults: &defaults
  site_name: "Super Awesome Twitter Machine!!"

development:
  domain: "172.16.11.32:3000"
  smtp_server: "172.16.11.32"
  smtp_port: 1025
  <<: *defaults

test:
  domain: test.host
  <<: *defaults

production:
  domain: ""
  smtp_server: ""
  smtp_port: 25
  <<: *defaults
